version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    expose:
      - '3000'
    depends_on:
      - db
    networks:
      - app-connect
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Todo
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - app-connect
volumes:
  db:
    driver: local

networks:
  app-connect:
      driver: bridge